version: '3'

services:

  server:
    ports:
      - '3000:3000' # Host:Container
    env_file:
      - local.env
    command: ["./wait-for-it.sh", "server_db:5432", "--", "npm", "run", "start:dev"]
    
  server_db:
    ports:
      - '5432:5432' # Host:Container
    env_file:
      - local.env