version: '3'

services:

  server:
    container_name: server
    build: ./server
    image: visual_text_server:1
    volumes:
      - './server:/visual_text/server'
      - '/visual_text/server/node_modules'
    depends_on:
      - server_db
    networks:
      - server_network
    
  server_db:
    container_name: server_db
    image: postgres:10.4
    volumes:
      - './server/src/db:/docker-entrypoint-initdb.d/'
      - './server/src/db:/visual_text/server_db'
    networks:
      - server_network

networks:
  server_network:
