version: '3'

services:

  server:
    container_name: server
    build: ./server
    image: visual_text_server:1
    volumes:
      - './server:/visual_text/server'
      - '/server/node_modules'
    ports:
      - '3000:3000' # Host:Container
    env_file:
      - local.env
    depends_on:
      - server_db
    command: ["./wait-for-it.sh", "server_db:5432", "--", "npm", "start"]
    networks:
      - server_network
    
  server_db:
    container_name: server_db
    image: postgres:10.4
    volumes:
      - './server/src/db:/docker-entrypoint-initdb.d/'
      - './server/src/db:/visual_text/server_db'
    ports:
      - '5432:5432' # Host:Container
    env_file:
      - local.env
    networks:
      - server_network

networks:
  server_network:
